### ISSUE TITLE
TODO List - Milestone Red-Social-Asociacion v0.1

### ISSUE THREAD

**Issue by francoa** [MecatronicaUncu/Red-Social-Asociacion#58]
Propongo este issue, como parte del milestone 0.1, para que listemos las funcionalidades que debe tener el entregable y que sean testeadas.

De esta forma podemos armar un branch release en el que quede dicho entregable para tenerlo como carta de presentación.

En teoría si hubiésemos trabajado "bien" desde el principio, listaríamos las funcionalidades (que se corresponderían 1 a 1 con branches) y haríamos merge de esas funcionalidades a un branch release "virgen". Considero que esta forma de trabajar es tal vez más complicada y contraintuitiva, pero sé que sirve cuando hay entregas importantes en medio del desarrollo. Si uno hace merge de las funcionalidades a develop y después el branch release es una mera copia del develop se corre el riesgo de entregar funcionalidades que todavía no han sido aprobadas y, peor aún, que no han pasado tests de integración o no han sido completadas.

**Sign Up** 
- [ ] Pedido de datos
- [ ] Verificación de los datos ingresados (no usuarios repetidos, longitud y validez de password)
- [ ] Creación de nuevo usuario
- [x] Envío de mail de activación #64 
- [x] Mail de activación #64 
- [ ] Cuenta inactiva (impedir log in o acceso a cualquier funcionalidad de la red)
- [x] Activación de usuario #64 

**Log In**
- [ ] Pedido de datos
- [ ] Verificación de los datos ingresados
- [ ] Contraseña olvidada
- [ ] Log in de usuario

**Cookies**
- [ ] Verificación de usuario ya loggeado
- [ ] Imposibilitar a usuarios realizar cambios en perfiles de otros usuarios

**Search**
- [ ] Búsqueda a través de distintos criterios
- [ ] Búsqueda referenciando participación en institución (andres@MecatronicaUncu)

**Profile**
- [ ] Creación de un perfil estándar para nuevos usuarios
- [ ] Cambio de foto de perfil, probar con distintos formatos y tamaños #65 
- [ ] Update de datos, probar con datos de longitudes o tipos erróneos
- [ ] Cambio de contraseña, verificar validez de antigua y nueva 
- [ ] Eliminación de usuario
- [ ] Correcta visualización de amistades
- [ ] Datos personales

**Friends**
- [x] Pedido de amistad #23 
- [x] Aceptación de amistad #23 
- [ ] Sugerencias de amistades

**General**
- [ ] Unit Tests!! #56 
- [ ] Chat
- [ ] Presentación (CSS)
- [ ] Responsiveness
- [x] Sacar a MongoDB #84 #83 

**EDT** (0.1 o 0.2?)
- [x] Funcionalidad básica #83
- [x] Favoritos #16
- [ ] Limpiar Controller. Ver comentarios en #21

**Comment by francoa** [comment]
Voy a arrancar a listar algunas. Todas se pueden discutir. El que siga, que copie las que ya están en la lista y agregue al final.

**Comment by andresmanelli** [comment]
Creo que se pueden editar los comentarios. Preferís que editemos uno general o que hagamos copy-paste?

**Comment by francoa** [comment]
Editado por Andrés: Ahora en el Issue aparece "0 de 30"

**Comment by francoa** [comment]
Editemos ese que acabo de hacer

**Comment by francoa** [comment]
hacerse una copia de la edición antes de poner update, por las dudas jajaj

**Comment by fcladera** [comment]
On November 12, 2015 11:06:55 PM GMT-03:00, Franco Ardiani notifications@github.com wrote:

> Propongo este issue, como parte del milestone 0.1, para que listemos
> las funcionalidades que debe tener el entregable y que sean testeadas.
> 
> De esta forma podemos armar un branch release en el que quede dicho
> entregable para tenerlo como carta de presentación.
> 
> En teoría si hubiésemos trabajado "bien" desde el principio,
> listaríamos las funcionalidades (que se corresponderían 1 a 1 con
> branches) y haríamos merge de esas funcionalidades a un branch release
> "virgen". Considero que esta forma de trabajar es tal vez más
> complicada y contraintuitiva, pero sé que sirve cuando hay entregas
> importantes en medio del desarrollo. Si uno hace merge de las
> funcionalidades a develop y después el branch release es una mera copia
> del develop se corre el riesgo de entregar funcionalidades que todavía
> no han sido aprobadas y, peor aún, que no han pasado tests de
> integración o no han sido completadas.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/58

No lo sé, estoy tomando cerveza.

**Comment by francoa** [comment]
https://docs.google.com/spreadsheets/d/1l592dkQEYmRsrh_s1ihrVA4_vwCr5N5bToc8ydgk4Iw/edit?usp=sharing

**Comment by francoa** [comment]
Bueno la idea ahora sería ir relevando todos los detalles incluídos en este milestone (ya lo hizo Andrés en el docs) e ir marcando los que están listos. Cuando todos estén listos, se hace un test final de integración y se saca el release.

**Comment by andresmanelli** [comment]
Les parece que volvamos a trabajar de a poco sobre esto?

**Comment by fcladera** [comment]
Oh por dios, está tratando de renacer!

**Comment by andresmanelli** [comment]
Voy a tirar un par de P.R para terminar de organizar el código y a partir de ahí hagamos lo que dijo @francoa de crear el branch `v-0.1` y meter todo ahí les parece? Tal vez habría que limpiar y acomodar las funcionalidades de nuevo. El que dice "unit tests" es como redundante jaja. 

Que no decaiga, ya casi estamos.

**Comment by fcladera** [comment]
Estaba pensando crear un container de docker con todo el proyecto.

**Comment by andresmanelli** [comment]
Eso con el fin de hacer deploy? o cómo lo usarías?

**Comment by fcladera** [comment]
On Friday, March 11, 2016 11:50:53 PM ART, Andrés wrote:

> Eso con el fin de hacer deploy? o cómo lo usarías?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MecatronicaUncu/Red-Social-Asociacion/issues/58#issuecomment-195645461

Si, así todos desarrollamos con lo mismo de base. Porque a veces tengo 
errores con la db que estimo deben ser por el so, sigue hinchando las bolas 
con el tema del nº de usuarios (algo que antes no hacía).

Docker para estas cosas es la posta. Uds usan ubuntu? Qué ubuntu?

**Comment by andresmanelli** [comment]
Yo tengo Arch. Franco creo que el 14.04 pero no sé. Lo de neo si te tira error, fijate lo que puse una vez no sé dónde:

[problema con lsof>=4.87](https://github.com/neo4j/neo4j/pull/5601/files)

**Comment by fcladera** [comment]
On Saturday, March 12, 2016 12:03:42 AM ART, Andrés wrote:

> Yo tengo Arch. Franco creo que el 14.04 pero no sé. Lo de neo 
> si te tira error, fijate lo que puse una vez no sé dónde:
> 
> [problema con lsof>=4.87](https://github.com/neo4j/neo4j/pull/5601/files)

Ok, lo voy a ver con eso a ver si se arregla.

Igual si tengo tiempo hago el container haha

**Comment by francoa** [comment]
14.04 LTS yo

**Comment by fcladera** [comment]
Igual voy a construirlo on top de 16.04 porque viene un poco más actualizado. Nos pegaremos a la próxima LTS, cuando salga.
